import React, { useState, useEffect } from 'react';
import { 
  Calculator, 
  Plus, 
  Trash2, 
  ArrowRight, 
  Sparkles, 
  CheckCircle2, 
  Sliders, 
  RefreshCw
} from 'lucide-react';
import { Product, PackagingLineItem, PackagingMaterialMaster } from '../../types';
import { calculationEngine } from '../../services/calculationEngine';

interface ApproachCalculatedProps {
  product: Product;
  availableMaterials: PackagingMaterialMaster[];
  onComplete: (data: {
    productQuantity: number;
    materials: PackagingLineItem[];
    notes?: string;
  }) => void;
  onBack: () => void;
}

export const ApproachCalculated: React.FC<ApproachCalculatedProps> = ({
  product,
  availableMaterials,
  onComplete,
  onBack,
}) => {
  const [productQuantity, setProductQuantity] = useState<number>(100);
  const [calculatedItems, setCalculatedItems] = useState<PackagingLineItem[]>([]);
  const [ruleExplanations, setRuleExplanations] = useState<string[]>([]);
  const [notes, setNotes] = useState('Recommended packaging generated by Cummins Top-Down Rule Engine based on product geometry and fragility rating.');

  const runCalculation = (qty: number) => {
    const res = calculationEngine.calculatePackagingBOM(product, qty);
    setCalculatedItems(res.recommendedMaterials);
    setRuleExplanations(res.ruleExplanations);
  };

  useEffect(() => {
    runCalculation(productQuantity);
  }, [product, productQuantity]);

  const handleResetToRules = () => {
    runCalculation(productQuantity);
  };

  const handleAddCustomMaterial = () => {
    const unused = availableMaterials.find(m => !calculatedItems.some(item => item.materialId === m.id)) || availableMaterials[0];
    const defaultWeightKg = 0.1 * productQuantity;

    const newItem: PackagingLineItem = {
      id: `calc-custom-${Date.now()}`,
      materialId: unused.id,
      materialName: unused.name,
      category: unused.category,
      quantity: unused.stockUnit === 'pcs' ? productQuantity : defaultWeightKg,
      unit: unused.stockUnit,
      weight: defaultWeightKg,
      weightUnit: 'kg',
      weightKg: defaultWeightKg,
      isSystemGenerated: false,
      notes: 'Added manually by operator to reinforce shipment.'
    };

    setCalculatedItems([...calculatedItems, newItem]);
  };

  const handleRemoveItem = (id: string) => {
    if (calculatedItems.length <= 1) return;
    setCalculatedItems(calculatedItems.filter(item => item.id !== id));
  };

  const handleItemMaterialChange = (id: string, materialId: string) => {
    const master = availableMaterials.find(m => m.id === materialId) || availableMaterials[0];
    setCalculatedItems(calculatedItems.map(item => {
      if (item.id === id) {
        return {
          ...item,
          materialId: master.id,
          materialName: master.name,
          category: master.category,
          unit: master.stockUnit,
          isSystemGenerated: false
        };
      }
      return item;
    }));
  };

  const handleItemQuantityChange = (id: string, newQty: number) => {
    const safeQty = Math.max(0, newQty);
    setCalculatedItems(calculatedItems.map(item => {
      if (item.id === id) {
        const master = availableMaterials.find(m => m.id === item.materialId);
        let calcWeightKg = safeQty;
        if (item.unit === 'pcs') {
          calcWeightKg = safeQty * (master?.weightPerUnitKg || 0.45);
        } else if (item.unit === 'g') {
          calcWeightKg = safeQty / 1000;
        }

        return {
          ...item,
          quantity: safeQty,
          weight: parseFloat(calcWeightKg.toFixed(3)),
          weightKg: parseFloat(calcWeightKg.toFixed(3)),
          isSystemGenerated: false
        };
      }
      return item;
    }));
  };

  const totalBatchWeightKg = calculatedItems.reduce((sum, item) => sum + (item.weightKg || 0), 0);
  const perUnitWeightKg = productQuantity > 0 ? totalBatchWeightKg / productQuantity : 0;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onComplete({
      productQuantity: Math.max(1, productQuantity),
      materials: calculatedItems,
      notes
    });
  };

  return (
    <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Context Banner */}
      <div className="glass-card" style={{ borderLeft: '4px solid var(--method-calculated)', background: '#FFFFFF' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
              <span className="badge badge-calculated">
                <Calculator size={12} /> Approach B
              </span>
              <span style={{ fontSize: '0.8rem', color: '#64748B' }}>
                System Calculated / Top-Down Rule Engine
              </span>
            </div>
            <h2 style={{ fontSize: '1.35rem', fontWeight: 800, color: '#0F172A' }}>
              Automated Packaging Composition & BOM Recommendation
            </h2>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <div style={{ background: '#FAF5FF', border: '1px solid #DDD6FE', padding: '6px 14px', borderRadius: '8px', textAlign: 'right' }}>
              <div style={{ fontSize: '0.7rem', color: '#7C3AED', fontWeight: 700, textTransform: 'uppercase' }}>
                Product Sizing Profile
              </div>
              <div className="font-mono font-bold" style={{ color: '#0F172A' }}>
                {product.weightKg} kg • {product.dimensionsCm.length}×{product.dimensionsCm.width}×{product.dimensionsCm.height} cm
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Rule Engine Logic Explanation Banner */}
      <div className="glass-card" style={{ background: '#FAF5FF', border: '1px solid #DDD6FE' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Sparkles size={16} color="#7C3AED" />
            <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#0F172A' }}>
              Rule Engine Calculation Basis
            </h3>
          </div>

          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={handleResetToRules}
            style={{ fontSize: '0.72rem', padding: '0.25rem 0.6rem' }}
          >
            <RefreshCw size={12} />
            <span>Reset to System Defaults</span>
          </button>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.6rem' }}>
          {ruleExplanations.map((exp, idx) => (
            <div key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '0.5rem', fontSize: '0.78rem', color: '#5B21B6', background: '#FFFFFF', padding: '7px 10px', borderRadius: '6px', border: '1px solid #DDD6FE' }}>
              <CheckCircle2 size={14} color="#7C3AED" style={{ marginTop: '1px', flexShrink: 0 }} />
              <span>{exp}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Main Configuration & Interactive BOM */}
      <div className="grid-cols-12">
        {/* Left Column: BOM Editor (8 cols) */}
        <div style={{ gridColumn: 'span 8' }} className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
            <div>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#0F172A' }}>
                Recommended Materials (Editable)
              </h3>
              <p style={{ fontSize: '0.8rem', color: '#64748B' }}>
                Modify calculated quantities or add custom packaging protections
              </p>
            </div>

            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={handleAddCustomMaterial}
            >
              <Plus size={14} />
              <span>Add Extra Material</span>
            </button>
          </div>

          {/* Batch Volume Input */}
          <div style={{ background: '#F8FAFC', padding: '0.85rem 1rem', borderRadius: '8px', border: '1px solid #E2E8F0', marginBottom: '1.25rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div>
              <div style={{ fontSize: '0.85rem', fontWeight: 600, color: '#0F172A' }}>
                Batch Production Quantity
              </div>
              <div style={{ fontSize: '0.75rem', color: '#64748B' }}>
                Multiplies per-unit recommendation to total batch mass
              </div>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <input
                type="number"
                min="1"
                step="1"
                className="form-input font-mono"
                value={productQuantity}
                onChange={(e) => setProductQuantity(Math.max(1, parseInt(e.target.value) || 1))}
                style={{ width: '110px', textAlign: 'right' }}
                required
              />
              <span className="text-xs text-muted">units</span>
            </div>
          </div>

          {/* Materials Table */}
          <div className="table-wrapper" style={{ marginBottom: '1.25rem' }}>
            <table className="custom-table">
              <thead>
                <tr>
                  <th>Packaging Material</th>
                  <th>Category</th>
                  <th style={{ width: '140px' }}>Quantity</th>
                  <th>Total Mass (kg)</th>
                  <th style={{ textAlign: 'right', width: '50px' }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {calculatedItems.map((item) => {
                  return (
                    <tr key={item.id}>
                      <td>
                        <div>
                          <select
                            className="form-select"
                            value={item.materialId}
                            onChange={(e) => handleItemMaterialChange(item.id, e.target.value)}
                            style={{ padding: '0.35rem 0.6rem', fontSize: '0.85rem', marginBottom: '3px' }}
                          >
                            {availableMaterials.map((m) => (
                              <option key={m.id} value={m.id}>
                                {m.name}
                              </option>
                            ))}
                          </select>
                          {item.isSystemGenerated ? (
                            <span style={{ fontSize: '0.68rem', color: '#7C3AED', display: 'flex', alignItems: 'center', gap: '3px', fontWeight: 600 }}>
                              <Sparkles size={10} /> System Recommended
                            </span>
                          ) : (
                            <span style={{ fontSize: '0.68rem', color: '#059669', display: 'flex', alignItems: 'center', gap: '3px', fontWeight: 600 }}>
                              <Sliders size={10} /> Operator Modified
                            </span>
                          )}
                        </div>
                      </td>
                      <td>
                        <span className="badge badge-neutral" style={{ fontSize: '0.7rem' }}>
                          {item.category}
                        </span>
                      </td>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                          <input
                            type="number"
                            min="0.01"
                            step="0.01"
                            className="form-input font-mono"
                            value={item.quantity}
                            onChange={(e) => handleItemQuantityChange(item.id, parseFloat(e.target.value) || 0)}
                            style={{ padding: '0.35rem 0.5rem', fontSize: '0.85rem', width: '85px' }}
                            required
                          />
                          <span className="font-mono text-xs text-muted">{item.unit}</span>
                        </div>
                      </td>
                      <td>
                        <span className="font-mono font-semibold" style={{ color: '#0F172A' }}>
                          {item.weightKg.toFixed(3)} kg
                        </span>
                      </td>
                      <td style={{ textAlign: 'right' }}>
                        <button
                          type="button"
                          className="btn btn-outline-danger btn-sm"
                          onClick={() => handleRemoveItem(item.id)}
                          disabled={calculatedItems.length <= 1}
                          style={{ padding: '0.3rem 0.45rem' }}
                          title="Remove Material"
                        >
                          <Trash2 size={13} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <div className="form-group" style={{ margin: 0 }}>
            <label className="form-label">
              <span>Engineering / Rule Notes</span>
            </label>
            <input
              type="text"
              className="form-input"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="System calculation commentary..."
            />
          </div>
        </div>

        {/* Right Column: Calculated Totals & Per-Unit Preview (4 cols) */}
        <div style={{ gridColumn: 'span 4', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          <div className="glass-card" style={{ border: '1px solid #DDD6FE', background: '#FFFFFF' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.25rem' }}>
              <div style={{ padding: '6px', borderRadius: '6px', background: '#FAF5FF', color: '#7C3AED' }}>
                <Calculator size={18} />
              </div>
              <h3 style={{ fontSize: '1.05rem', fontWeight: 700, color: '#0F172A' }}>
                Calculated Metrics
              </h3>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem', marginBottom: '1.5rem' }}>
              <div style={{ padding: '0.75rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
                <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                  Per-Unit Packaging Mass
                </div>
                <div className="font-mono font-bold text-xl" style={{ color: '#7C3AED', marginTop: '2px' }}>
                  {perUnitWeightKg.toFixed(3)} <span style={{ fontSize: '0.9rem', color: '#64748B' }}>kg / unit</span>
                </div>
                <div style={{ fontSize: '0.72rem', color: '#64748B', marginTop: '3px' }}>
                  ≈ {Math.round(perUnitWeightKg * 1000)} grams per {product.name}
                </div>
              </div>

              <div style={{ padding: '0.75rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
                <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                  Total Batch Packaging Weight
                </div>
                <div className="font-mono font-bold text-xl" style={{ color: '#0F172A', marginTop: '2px' }}>
                  {totalBatchWeightKg.toFixed(2)} <span style={{ fontSize: '0.9rem', color: '#64748B' }}>kg</span>
                </div>
                <div style={{ fontSize: '0.72rem', color: '#64748B', marginTop: '3px' }}>
                  For batch of {productQuantity.toLocaleString()} units
                </div>
              </div>

              <div style={{ padding: '0.75rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
                <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                  Active Materials in BOM
                </div>
                <div className="font-mono font-bold text-lg" style={{ color: '#059669', marginTop: '2px' }}>
                  {calculatedItems.length} line items
                </div>
              </div>
            </div>

            <div style={{ fontSize: '0.75rem', color: '#64748B', background: '#FAF5FF', padding: '8px 10px', borderRadius: '6px', border: '1px solid #DDD6FE' }}>
              ⚡ In production, these calculations execute via the Cummins Engineering Packaging Rules API.
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Action Controls */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '0.5rem' }}>
        <button type="button" className="btn btn-secondary" onClick={onBack}>
          Back to Method Selection
        </button>

        <button type="submit" className="btn btn-primary btn-lg">
          <span>Proceed to Packaging Summary Review</span>
          <ArrowRight size={18} />
        </button>
      </div>
    </form>
  );
};
