import React, { useState } from 'react';
import { 
  CheckCircle2, 
  ArrowLeft, 
  Database, 
  Calculator, 
  Edit3, 
  ShieldCheck, 
  Clock,
  Send,
  X,
  Leaf,
  FileText
} from 'lucide-react';
import { 
  Product, 
  PackagingLineItem, 
  RecordingMethod, 
  PpwrSummaryBreakdown,
  RecordStatus
} from '../../types';
import { recordsService } from '../../services/recordsService';

interface PackagingSummaryProps {
  product: Product;
  productQuantity: number;
  method: RecordingMethod;
  materials: PackagingLineItem[];
  period?: string;
  notes?: string;
  onSave: (status: RecordStatus) => void;
  onBackToEdit: () => void;
}

export const PackagingSummary: React.FC<PackagingSummaryProps> = ({
  product,
  productQuantity,
  method,
  materials,
  period,
  notes,
  onSave,
  onBackToEdit,
}) => {
  const [showExportModal, setShowExportModal] = useState(false);
  const ppwrSummary: PpwrSummaryBreakdown = recordsService.calculatePpwrSummary(materials, productQuantity);

  // EU PPWR Recyclability Grade (A to D)
  const getRecyclabilityGrade = (pct: number): { grade: string; color: string; bg: string; label: string } => {
    if (pct >= 95) return { grade: 'A', color: '#065F46', bg: '#ECFDF5', label: 'Excellent — Fully Recyclable (PPWR Preferred)' };
    if (pct >= 80) return { grade: 'B', color: '#1D4ED8', bg: '#EFF6FF', label: 'Good — Mostly Recyclable (PPWR Compliant)' };
    if (pct >= 60) return { grade: 'C', color: '#92400E', bg: '#FFFBEB', label: 'Moderate — Partially Recyclable (Improvement Needed)' };
    return { grade: 'D', color: '#991B1B', bg: '#FEF2F2', label: 'Poor — Low Recyclability (Non-Compliant Risk)' };
  };

  const grade = getRecyclabilityGrade(ppwrSummary.avgRecyclablePct);

  const getMethodBadge = () => {
    switch (method) {
      case 'INVENTORY':
        return <span className="badge badge-inventory"><Database size={12} /> Approach A — Inventory / Consumption</span>;
      case 'CALCULATED':
        return <span className="badge badge-calculated"><Calculator size={12} /> Approach B — System Calculated</span>;
      case 'USER_INPUT':
        return <span className="badge badge-user-input"><Edit3 size={12} /> Approach C — User Input Log</span>;
    }
  };

  const getMethodDescription = () => {
    switch (method) {
      case 'INVENTORY':
        return `Batch consumption allocated over ${period || 'accounting period'} across ${productQuantity.toLocaleString()} units (${ppwrSummary.perUnitPackagingWeightKg.toFixed(3)} kg/unit).`;
      case 'CALCULATED':
        return `Generated by Top-Down Rule Engine calibrated for ${product.weightKg} kg payload & ${product.dimensionsCm.length}×${product.dimensionsCm.width}×${product.dimensionsCm.height} cm profile.`;
      case 'USER_INPUT':
        return `Captured from packing station floor logs with verified unit mass measurements.`;
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', width: '100%', maxWidth: '1440px', margin: '0 auto' }}>
      {/* Header / Review Banner */}
      <div 
        className="glass-card" 
        style={{ 
          background: '#FFFFFF',
          border: '1px solid #E2E8F0',
          boxShadow: '0 1px 3px rgba(0, 0, 0, 0.04)',
          padding: '1.25rem 1.5rem'
        }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem', marginBottom: '1.25rem' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.4rem' }}>
              <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#DA291C', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                PPWR Compliance Verification
              </span>
              <span style={{ color: '#CBD5E1' }}>•</span>
              {getMethodBadge()}
            </div>
            <h1 style={{ fontSize: '1.4rem', fontWeight: 800, color: '#0F172A', margin: 0 }}>
              Packaging Bill-of-Materials & Summary Review
            </h1>
            <p style={{ fontSize: '0.82rem', color: '#64748B', marginTop: '3px' }}>
              {getMethodDescription()}
            </p>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' }}>
            <button 
              type="button" 
              className="btn btn-secondary btn-sm"
              onClick={onBackToEdit}
              style={{ padding: '8px 14px', fontSize: '0.82rem', fontWeight: 600 }}
            >
              <ArrowLeft size={15} />
              <span>Back to Station</span>
            </button>

            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={() => onSave('DRAFT')}
              title="Save as draft for shift supervisor review"
              style={{ padding: '8px 14px', fontSize: '0.82rem', fontWeight: 600 }}
            >
              <Clock size={15} />
              <span>Save Draft</span>
            </button>

            <button
              type="button"
              className="btn btn-primary"
              onClick={() => onSave('CONFIRMED')}
              style={{ padding: '8px 20px', fontSize: '0.85rem', fontWeight: 700 }}
            >
              <CheckCircle2 size={16} />
              <span>Confirm & Submit Record</span>
            </button>
          </div>
        </div>

        {/* Product & Scope Specs Bar */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem', background: '#F8FAFC', padding: '0.85rem 1.25rem', borderRadius: '10px', border: '1px solid #E2E8F0' }}>
          <div>
            <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Product SKU / Name</div>
            <div className="font-mono font-bold text-sm" style={{ color: '#0F172A' }}>
              {product.sku} • {product.name}
            </div>
          </div>

          <div>
            <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Batch Quantity</div>
            <div className="font-mono font-bold text-sm" style={{ color: '#0284C7' }}>
              {productQuantity.toLocaleString()} units
            </div>
          </div>

          <div>
            <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Total Packaging Mass</div>
            <div className="font-mono font-bold text-sm" style={{ color: '#DA291C' }}>
              {ppwrSummary.totalPackagingWeightKg.toFixed(2)} kg
            </div>
          </div>

          <div>
            <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Per-Unit Consumption</div>
            <div className="font-mono font-bold text-sm" style={{ color: '#059669' }}>
              {ppwrSummary.perUnitPackagingWeightKg.toFixed(3)} kg/unit
            </div>
          </div>
        </div>
      </div>

      {/* Main Material BOM Table */}
      <div className="glass-card">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
          <div>
            <h3 style={{ fontSize: '1.15rem', fontWeight: 700, color: '#0F172A' }}>
              Recorded Material Bill-of-Materials (BOM)
            </h3>
            <p style={{ fontSize: '0.8rem', color: '#64748B' }}>
              Standardized packaging line items ready for PPWR compliance ledger
            </p>
          </div>
          <span style={{ fontSize: '0.75rem', fontFamily: 'var(--font-mono)', color: '#64748B' }}>
            {materials.length} Material Line Items
          </span>
        </div>

        <div className="table-wrapper" style={{ marginBottom: '1.5rem', overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
          <table className="custom-table" style={{ minWidth: '860px', width: '100%' }}>
            <thead>
              <tr>
                <th style={{ width: '110px' }}>Material ID</th>
                <th style={{ width: '200px' }}>Material Description</th>
                <th style={{ width: '130px' }}>PPWR Category</th>
                <th style={{ width: '110px' }}>Quantity / Unit</th>
                <th style={{ width: '110px' }}>Total Pkg Mass</th>
                <th style={{ width: '110px' }}>Pkg Mass / Unit</th>
                <th style={{ width: '90px' }}>% Share</th>
                <th style={{ minWidth: '160px' }}>Line Notes</th>
              </tr>
            </thead>
            <tbody>
              {materials.map((mat) => {
                const itemTotalKg = mat.weightKg || 0;
                const perUnitKg = productQuantity > 0 ? itemTotalKg / productQuantity : 0;
                const sharePct = ppwrSummary.totalPackagingWeightKg > 0 
                  ? Math.round((itemTotalKg / ppwrSummary.totalPackagingWeightKg) * 100) 
                  : 0;

                return (
                  <tr key={mat.id}>
                    <td>
                      <span className="font-mono text-xs font-semibold" style={{ color: '#64748B' }}>
                        {mat.materialId}
                      </span>
                    </td>
                    <td>
                      <div style={{ fontWeight: 600, color: '#0F172A' }}>
                        {mat.materialName}
                      </div>
                    </td>
                    <td>
                      <span className="badge badge-neutral" style={{ fontSize: '0.72rem' }}>
                        {mat.category}
                      </span>
                    </td>
                    <td>
                      <span className="font-mono">
                        {mat.quantity.toLocaleString()} {mat.unit}
                      </span>
                    </td>
                    <td>
                      <span className="font-mono font-bold" style={{ color: '#DA291C' }}>
                        {itemTotalKg.toFixed(3)} kg
                      </span>
                    </td>
                    <td>
                      <span className="font-mono text-xs" style={{ color: '#0284C7' }}>
                        {perUnitKg >= 0.001 ? perUnitKg.toFixed(3) : perUnitKg.toFixed(4)} kg/u
                      </span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                        <div style={{ width: '40px', height: '6px', background: '#E2E8F0', borderRadius: '3px', overflow: 'hidden' }}>
                          <div style={{ width: `${sharePct}%`, height: '100%', background: mat.category === 'Plastic' ? '#DB2777' : '#D97706' }} />
                        </div>
                        <span className="font-mono text-xs text-muted">{sharePct}%</span>
                      </div>
                    </td>
                    <td style={{ maxWidth: '240px' }}>
                      <span 
                        style={{ 
                          fontSize: '0.72rem', 
                          color: '#475569', 
                          background: '#F8FAFC', 
                          padding: '3px 8px', 
                          borderRadius: '4px', 
                          border: '1px solid #E2E8F0',
                          display: 'inline-block',
                          lineHeight: '1.3'
                        }}
                      >
                        {mat.notes || 'Standard packaging allocation'}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {/* Material Category Fractions Card Grid */}
        <div style={{ borderTop: '1px solid var(--border-subtle)', paddingTop: '1.25rem' }}>
          <h4 style={{ fontSize: '0.92rem', fontWeight: 700, color: '#0F172A', marginBottom: '0.85rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <ShieldCheck size={17} color="#059669" />
            Material Category Breakdown
          </h4>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem' }}>
            {/* Paper / Cardboard */}
            <div style={{ padding: '1rem 1.25rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                Paper & Cardboard Mass
              </div>
              <div className="font-mono font-bold text-xl" style={{ color: '#D97706', marginTop: '3px' }}>
                {ppwrSummary.paperCardboardKg.toFixed(2)} kg
              </div>
              <div style={{ fontSize: '0.75rem', color: '#475569', marginTop: '2px' }}>
                <strong>{ppwrSummary.paperCardboardPct}%</strong> of total packaging
              </div>
            </div>

            {/* Plastic Fraction */}
            <div style={{ padding: '1rem 1.25rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                Polymer & Plastic Mass
              </div>
              <div className="font-mono font-bold text-xl" style={{ color: '#DB2777', marginTop: '3px' }}>
                {ppwrSummary.plasticKg.toFixed(2)} kg
              </div>
              <div style={{ fontSize: '0.75rem', color: '#475569', marginTop: '2px' }}>
                <strong>{ppwrSummary.plasticPct}%</strong> of total packaging
              </div>
            </div>
          </div>
        </div>

        {/* Live Inventory Auto-Deduction Notice */}
        <div style={{ marginTop: '1.25rem', padding: '0.65rem 0.95rem', background: '#F0FDF4', borderRadius: '8px', border: '1px solid #BBF7D0', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '0.5rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
            <span className="badge" style={{ fontSize: '0.72rem', background: '#DCFCE7', color: '#15803D', border: '1px solid #86EFAC', fontWeight: 700 }}>
              <Database size={11} /> Live Stock Sync
            </span>
            <span style={{ fontSize: '0.8rem', color: '#166534', fontWeight: 600 }}>
              Confirming this record will automatically deduct consumed packaging materials from the plant warehouse inventory.
            </span>
          </div>
        </div>

        {notes && (
          <div style={{ marginTop: '0.75rem', padding: '0.75rem 1rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
            <span style={{ fontSize: '0.75rem', color: '#64748B', fontWeight: 600, textTransform: 'uppercase' }}>
              Record Audit Notes:
            </span>
            <p style={{ fontSize: '0.85rem', color: '#334155', marginTop: '2px' }}>
              {notes}
            </p>
          </div>
        )}
      </div>

      {/* Bottom Action Bar */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#FFFFFF', padding: '1rem 1.5rem', borderRadius: '12px', border: '1px solid #E2E8F0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
        <button 
          type="button" 
          className="btn btn-secondary btn-sm"
          onClick={onBackToEdit}
          style={{ padding: '8px 14px', fontSize: '0.82rem', fontWeight: 600 }}
        >
          <ArrowLeft size={15} />
          <span>Back to Station</span>
        </button>

        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={() => onSave('DRAFT')}
            style={{ padding: '8px 14px', fontSize: '0.82rem', fontWeight: 600 }}
          >
            <Clock size={15} />
            <span>Save Draft</span>
          </button>

          <button
            type="button"
            className="btn btn-primary"
            onClick={() => onSave('CONFIRMED')}
            style={{ padding: '8px 20px', fontSize: '0.85rem', fontWeight: 700 }}
          >
            <CheckCircle2 size={16} />
            <span>Confirm & Submit Record</span>
          </button>
        </div>
      </div>

      {/* PPWR ESG Downstream Export Modal */}
      {showExportModal && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(15,23,42,0.55)', zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }}>
          <div style={{ background: '#FFFFFF', borderRadius: '16px', width: '100%', maxWidth: '680px', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.35)', overflow: 'hidden' }}>
            {/* Modal Header */}
            <div style={{ background: 'linear-gradient(135deg, #7C3AED 0%, #6D28D9 100%)', padding: '1.25rem 1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.75)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '4px' }}>
                  Downstream Dispatch — PPWR Compliance Engine
                </div>
                <h3 style={{ color: '#FFFFFF', fontWeight: 800, fontSize: '1.1rem', margin: 0 }}>
                  Export Packaging Record to Compliance Systems
                </h3>
              </div>
              <button onClick={() => setShowExportModal(false)} style={{ background: 'rgba(255,255,255,0.15)', border: 'none', borderRadius: '8px', color: '#FFFFFF', padding: '6px', cursor: 'pointer' }}>
                <X size={18} />
              </button>
            </div>

            <div style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {/* Record Summary Strip */}
              <div style={{ background: '#F8FAFC', borderRadius: '10px', padding: '1rem', border: '1px solid #E2E8F0', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem' }}>
                <div>
                  <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Product SKU</div>
                  <div style={{ fontWeight: 800, fontFamily: 'var(--font-mono)', color: '#DA291C' }}>{product.sku}</div>
                </div>
                <div>
                  <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Total Packaging Mass</div>
                  <div style={{ fontWeight: 800, fontFamily: 'var(--font-mono)', color: '#0F172A' }}>{ppwrSummary.totalPackagingWeightKg.toFixed(3)} kg</div>
                </div>
                <div>
                  <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>PPWR Grade</div>
                  <div style={{ fontWeight: 900, fontFamily: 'var(--font-mono)', color: grade.color, fontSize: '1.15rem' }}>Grade {grade.grade}</div>
                </div>
              </div>

              {/* Export Targets */}
              <div style={{ fontSize: '0.82rem', fontWeight: 700, color: '#0F172A', marginBottom: '2px' }}>Select Downstream Export Target:</div>
              {[
                { icon: '🇪🇺', title: 'EU PPWR Digital Product Passport (DPP)', sub: 'Submit to European Single Market compliance portal (Article 9 & 10 verification)', status: 'Ready to Submit', statusColor: '#059669' },
                { icon: '🌱', title: 'Cummins Corporate ESG / Scope 3 Data Lake', sub: `Dispatch packaging CO₂e: ${ppwrSummary.estimatedCo2eKg.toFixed(2)} kg to IntegrityNext sustainability platform`, status: 'Ready to Submit', statusColor: '#059669' },
                { icon: '💼', title: 'SAP ERP Financial Ledger (EPR/Plastic Tax)', sub: 'Dispatch plastic mass for Extended Producer Responsibility fee calculation', status: 'Ready to Submit', statusColor: '#059669' },
                { icon: '📄', title: 'Audit-Ready PDF Compliance Dossier', sub: 'Generate official tamper-evident certificate with cryptographic ledger hash', status: 'Generate PDF', statusColor: '#7C3AED' },
              ].map((target, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 14px', border: '1px solid #E2E8F0', borderRadius: '10px', background: '#FAFAFA', gap: '12px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flex: 1 }}>
                    <span style={{ fontSize: '1.4rem' }}>{target.icon}</span>
                    <div>
                      <div style={{ fontWeight: 700, color: '#0F172A', fontSize: '0.85rem' }}>{target.title}</div>
                      <div style={{ fontSize: '0.72rem', color: '#64748B', marginTop: '2px' }}>{target.sub}</div>
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      setTimeout(() => alert(`✅ Successfully dispatched to: ${target.title}\n\nThis would send the normalized PPWR compliance payload to the target system in a live environment.`), 100);
                    }}
                    style={{ background: target.statusColor, color: '#FFFFFF', border: 'none', borderRadius: '7px', padding: '6px 14px', fontWeight: 700, fontSize: '0.75rem', cursor: 'pointer', whiteSpace: 'nowrap' }}
                  >
                    {target.status}
                  </button>
                </div>
              ))}

              {/* JSON Preview */}
              <div>
                <div style={{ fontSize: '0.78rem', fontWeight: 700, color: '#475569', marginBottom: '6px', display: 'flex', alignItems: 'center', gap: '5px' }}>
                  <FileText size={13} /> PPWR Normalized Payload Preview (JSON)
                </div>
                <pre style={{ background: '#0F172A', color: '#A3E635', padding: '14px', borderRadius: '8px', fontSize: '0.72rem', fontFamily: 'var(--font-mono)', overflowX: 'auto', margin: 0, maxHeight: '160px', overflowY: 'auto' }}>
{`{
  "ppwr_record_id": "PR-${Date.now().toString().slice(-6)}",
  "product_sku": "${product.sku}",
  "product_name": "${product.name}",
  "batch_quantity": ${productQuantity},
  "total_packaging_kg": ${ppwrSummary.totalPackagingWeightKg.toFixed(3)},
  "per_unit_kg": ${ppwrSummary.perUnitPackagingWeightKg.toFixed(4)},
  "paper_cardboard_kg": ${ppwrSummary.paperCardboardKg.toFixed(3)},
  "plastic_kg": ${ppwrSummary.plasticKg.toFixed(3)},
  "recyclability_pct": ${ppwrSummary.avgRecyclablePct},
  "ppwr_grade": "${grade.grade}",
  "co2e_kg": ${ppwrSummary.estimatedCo2eKg.toFixed(3)},
  "recording_method": "${method}",
  "compliance_standard": "EU PPWR 2024 (Art. 9 & 10)",
  "cummins_plant": "IN-PUN-01",
  "timestamp": "${new Date().toISOString()}"
}`}
                </pre>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
