import React from 'react';
import { 
  CheckCircle2, 
  ArrowLeft, 
  Database, 
  Calculator, 
  Edit3, 
  ShieldCheck, 
  Clock
} from 'lucide-react';
import { 
  Product, 
  PackagingLineItem, 
  RecordingMethod, 
  PpwrSummaryBreakdown,
  RecordStatus
} from '../../types';
import { recordsService } from '../../services/recordsService';

interface PackagingSummaryProps {
  product: Product;
  productQuantity: number;
  method: RecordingMethod;
  materials: PackagingLineItem[];
  period?: string;
  notes?: string;
  onSave: (status: RecordStatus) => void;
  onBackToEdit: () => void;
}

export const PackagingSummary: React.FC<PackagingSummaryProps> = ({
  product,
  productQuantity,
  method,
  materials,
  period,
  notes,
  onSave,
  onBackToEdit,
}) => {
  const ppwrSummary: PpwrSummaryBreakdown = recordsService.calculatePpwrSummary(materials, productQuantity);

  const getMethodBadge = () => {
    switch (method) {
      case 'INVENTORY':
        return <span className="badge badge-inventory"><Database size={12} /> Approach A — Inventory / Consumption</span>;
      case 'CALCULATED':
        return <span className="badge badge-calculated"><Calculator size={12} /> Approach B — System Calculated</span>;
      case 'USER_INPUT':
        return <span className="badge badge-user-input"><Edit3 size={12} /> Approach C — User Input Log</span>;
    }
  };

  const getMethodDescription = () => {
    switch (method) {
      case 'INVENTORY':
        return `Batch consumption allocated over ${period || 'accounting period'} across ${productQuantity.toLocaleString()} units (${ppwrSummary.perUnitPackagingWeightKg.toFixed(3)} kg/unit).`;
      case 'CALCULATED':
        return `Generated by Top-Down Rule Engine calibrated for ${product.weightKg} kg payload & ${product.dimensionsCm.length}×${product.dimensionsCm.width}×${product.dimensionsCm.height} cm profile.`;
      case 'USER_INPUT':
        return `Captured from packing station floor logs with verified unit mass measurements.`;
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Header / Review Banner */}
      <div 
        className="glass-card" 
        style={{ 
          background: '#FFFFFF',
          border: '1px solid #E2E8F0',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)'
        }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem', marginBottom: '1.25rem' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.4rem' }}>
              <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#DA291C', textTransform: 'uppercase' }}>
                Step 3 of 4: Common Review Screen
              </span>
              <span style={{ color: '#CBD5E1' }}>•</span>
              {getMethodBadge()}
            </div>
            <h1 style={{ fontSize: '1.5rem', fontWeight: 800, color: '#0F172A' }}>
              Packaging Bill-of-Materials & Summary Review
            </h1>
            <p style={{ fontSize: '0.85rem', color: '#475569', marginTop: '2px' }}>
              {getMethodDescription()}
            </p>
          </div>

          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button 
              type="button" 
              className="btn btn-secondary"
              onClick={onBackToEdit}
            >
              <ArrowLeft size={16} />
              <span>Back to Edit</span>
            </button>

            <button
              type="button"
              className="btn btn-secondary"
              onClick={() => onSave('DRAFT')}
              title="Save as draft for shift supervisor review"
            >
              <Clock size={16} />
              <span>Save as Draft</span>
            </button>

            <button
              type="button"
              className="btn btn-primary btn-lg"
              onClick={() => onSave('CONFIRMED')}
            >
              <CheckCircle2 size={18} />
              <span>Confirm & Commit Record</span>
            </button>
          </div>
        </div>

        {/* Product & Scope Specs Bar */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem', background: '#F8FAFC', padding: '0.85rem 1.25rem', borderRadius: '10px', border: '1px solid #E2E8F0' }}>
          <div>
            <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Product SKU / Name</div>
            <div className="font-mono font-bold text-sm" style={{ color: '#0F172A' }}>
              {product.sku} • {product.name}
            </div>
          </div>

          <div>
            <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Batch Quantity</div>
            <div className="font-mono font-bold text-sm" style={{ color: '#0284C7' }}>
              {productQuantity.toLocaleString()} units
            </div>
          </div>

          <div>
            <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Total Packaging Mass</div>
            <div className="font-mono font-bold text-sm" style={{ color: '#DA291C' }}>
              {ppwrSummary.totalPackagingWeightKg.toFixed(2)} kg
            </div>
          </div>

          <div>
            <div style={{ fontSize: '0.7rem', color: '#64748B', textTransform: 'uppercase' }}>Per-Unit Consumption</div>
            <div className="font-mono font-bold text-sm" style={{ color: '#059669' }}>
              {ppwrSummary.perUnitPackagingWeightKg.toFixed(3)} kg/unit
            </div>
          </div>
        </div>
      </div>

      {/* Main Material BOM Table */}
      <div className="glass-card">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
          <div>
            <h3 style={{ fontSize: '1.15rem', fontWeight: 700, color: '#0F172A' }}>
              Recorded Material Bill-of-Materials (BOM)
            </h3>
            <p style={{ fontSize: '0.8rem', color: '#64748B' }}>
              Standardized packaging line items ready for PPWR compliance ledger
            </p>
          </div>
          <span style={{ fontSize: '0.75rem', fontFamily: 'var(--font-mono)', color: '#64748B' }}>
            {materials.length} Material Line Items
          </span>
        </div>

        <div className="table-wrapper" style={{ marginBottom: '1.5rem' }}>
          <table className="custom-table">
            <thead>
              <tr>
                <th>Material ID</th>
                <th>Material Description</th>
                <th>PPWR Category</th>
                <th>Quantity / Unit</th>
                <th>Total Mass</th>
                <th>Per Unit Mass</th>
                <th>% Share</th>
                <th>Line Notes</th>
              </tr>
            </thead>
            <tbody>
              {materials.map((mat) => {
                const itemTotalKg = mat.weightKg || 0;
                const perUnitKg = productQuantity > 0 ? itemTotalKg / productQuantity : 0;
                const sharePct = ppwrSummary.totalPackagingWeightKg > 0 
                  ? Math.round((itemTotalKg / ppwrSummary.totalPackagingWeightKg) * 100) 
                  : 0;

                return (
                  <tr key={mat.id}>
                    <td>
                      <span className="font-mono text-xs font-semibold" style={{ color: '#64748B' }}>
                        {mat.materialId}
                      </span>
                    </td>
                    <td>
                      <div style={{ fontWeight: 600, color: '#0F172A' }}>
                        {mat.materialName}
                      </div>
                    </td>
                    <td>
                      <span className="badge badge-neutral" style={{ fontSize: '0.72rem' }}>
                        {mat.category}
                      </span>
                    </td>
                    <td>
                      <span className="font-mono">
                        {mat.quantity.toLocaleString()} {mat.unit}
                      </span>
                    </td>
                    <td>
                      <span className="font-mono font-bold" style={{ color: '#DA291C' }}>
                        {itemTotalKg.toFixed(3)} kg
                      </span>
                    </td>
                    <td>
                      <span className="font-mono text-xs" style={{ color: '#0284C7' }}>
                        {perUnitKg >= 0.001 ? perUnitKg.toFixed(3) : perUnitKg.toFixed(4)} kg/u
                      </span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                        <div style={{ width: '40px', height: '6px', background: '#E2E8F0', borderRadius: '3px', overflow: 'hidden' }}>
                          <div style={{ width: `${sharePct}%`, height: '100%', background: mat.category === 'Plastic' ? '#DB2777' : '#D97706' }} />
                        </div>
                        <span className="font-mono text-xs text-muted">{sharePct}%</span>
                      </div>
                    </td>
                    <td>
                      <span style={{ fontSize: '0.75rem', color: '#64748B' }}>
                        {mat.notes || 'Standard packaging allocation'}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {/* Material Category Fractions Card Grid */}
        <div style={{ borderTop: '1px solid var(--border-subtle)', paddingTop: '1.25rem' }}>
          <h4 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#0F172A', marginBottom: '0.85rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <ShieldCheck size={18} color="#059669" />
            Material Category & Recyclability Breakdown
          </h4>

          <div className="grid-cols-4">
            {/* Paper / Cardboard */}
            <div style={{ padding: '0.85rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                Paper & Cardboard Mass
              </div>
              <div className="font-mono font-bold text-lg" style={{ color: '#D97706', marginTop: '2px' }}>
                {ppwrSummary.paperCardboardKg.toFixed(2)} kg
              </div>
              <div style={{ fontSize: '0.75rem', color: '#475569', marginTop: '2px' }}>
                <strong>{ppwrSummary.paperCardboardPct}%</strong> of total packaging
              </div>
            </div>

            {/* Plastic Fraction */}
            <div style={{ padding: '0.85rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                Polymer & Plastic Mass
              </div>
              <div className="font-mono font-bold text-lg" style={{ color: '#DB2777', marginTop: '2px' }}>
                {ppwrSummary.plasticKg.toFixed(2)} kg
              </div>
              <div style={{ fontSize: '0.75rem', color: '#475569', marginTop: '2px' }}>
                <strong>{ppwrSummary.plasticPct}%</strong> of total packaging
              </div>
            </div>

            {/* Recyclability Score */}
            <div style={{ padding: '0.85rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                Avg Recyclable Content
              </div>
              <div className="font-mono font-bold text-lg" style={{ color: '#059669', marginTop: '2px' }}>
                {ppwrSummary.avgRecyclablePct}%
              </div>
              <div style={{ fontSize: '0.75rem', color: '#059669', marginTop: '2px' }}>
                ✓ Recyclable Materials
              </div>
            </div>

            {/* Carbon Footprint */}
            <div style={{ padding: '0.85rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <div style={{ fontSize: '0.72rem', color: '#64748B', textTransform: 'uppercase', fontWeight: 600 }}>
                Estimated Packaging CO₂e
              </div>
              <div className="font-mono font-bold text-lg" style={{ color: '#0284C7', marginTop: '2px' }}>
                {ppwrSummary.estimatedCo2eKg.toFixed(1)} kg
              </div>
              <div style={{ fontSize: '0.75rem', color: '#64748B', marginTop: '2px' }}>
                {(ppwrSummary.estimatedCo2eKg / productQuantity).toFixed(3)} kg CO₂e / unit
              </div>
            </div>
          </div>
        </div>

        {notes && (
          <div style={{ marginTop: '1.25rem', padding: '0.75rem 1rem', background: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
            <span style={{ fontSize: '0.75rem', color: '#64748B', fontWeight: 600, textTransform: 'uppercase' }}>
              Record Audit Notes:
            </span>
            <p style={{ fontSize: '0.85rem', color: '#334155', marginTop: '2px' }}>
              {notes}
            </p>
          </div>
        )}
      </div>

      {/* Bottom Action Bar */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#FFFFFF', padding: '1rem 1.5rem', borderRadius: '12px', border: '1px solid #E2E8F0', boxShadow: '0 2px 4px rgba(0,0,0,0.04)' }}>
        <button 
          type="button" 
          className="btn btn-secondary"
          onClick={onBackToEdit}
        >
          <ArrowLeft size={16} />
          <span>Back to Edit Materials</span>
        </button>

        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button
            type="button"
            className="btn btn-secondary"
            onClick={() => onSave('DRAFT')}
          >
            <Clock size={16} />
            <span>Save as Draft</span>
          </button>

          <button
            type="button"
            className="btn btn-primary btn-lg"
            onClick={() => onSave('CONFIRMED')}
          >
            <CheckCircle2 size={18} />
            <span>Confirm & Commit Record</span>
          </button>
        </div>
      </div>
    </div>
  );
};
